# PKGBUILD for Pdfium built against system ICU
# This builds Pdfium from source to match your system's ICU version
# Usage: makepkg -si

pkgname=pdfium-system-icu
pkgver=latest
pkgrel=1
pkgdesc="Pdfium library built against system ICU (compatible with ICU 78+)"
arch=('x86_64')
url="https://pdfium.googlesource.com/pdfium"
license=('BSD')
depends=('icu' 'freetype2' 'lcms2' 'openjpeg2' 'libjpeg-turbo' 'zlib')
makedepends=('git' 'python' 'ninja' 'gn' 'base-devel' 'gcc' 'binutils')
provides=('libpdfium')
conflicts=('pdfium-binaries')
options=('!strip')  # Don't strip - it removes exported symbols

prepare() {
  cd "$srcdir"
  
  # Install depot_tools first
  if [ ! -d "depot_tools" ]; then
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  fi
  
  export PATH="$PATH:$srcdir/depot_tools"
  
  # Clone Pdfium if not exists
  if [ ! -d "pdfium" ]; then
    git clone https://pdfium.googlesource.com/pdfium
  fi
  
  cd pdfium
  git pull
  
  # Configure gclient
  if [ ! -f ".gclient" ]; then
    cat > .gclient << 'EOF'
solutions = [
  {
    "name": "pdfium",
    "url": "https://pdfium.googlesource.com/pdfium.git",
    "deps_file": "DEPS",
    "managed": False,
  },
]
EOF
  fi
  
  # Fetch dependencies
  echo "Fetching dependencies (this may take a while)..."
  gclient sync
}

build() {
  export PATH="$PATH:$srcdir/depot_tools"
  
  # gclient sync creates a nested structure, find the actual pdfium directory
  if [ -d "$srcdir/pdfium/pdfium" ]; then
    cd "$srcdir/pdfium/pdfium"
  else
    cd "$srcdir/pdfium"
  fi
  
  # Configure build to use system ICU and libraries
  # Build as static library, then we'll create a shared library from it
  mkdir -p out/Default
  cat > out/Default/args.gn << 'EOF'
is_debug = false
is_component_build = false
pdf_enable_xfa = false
pdf_enable_v8 = false
pdf_use_skia = false
pdf_use_skia_paths = false
use_system_icu = true
use_system_freetype = true
use_system_lcms2 = true
use_system_libjpeg = true
use_system_libpng = true
use_system_zlib = true
use_libfuzzer = false
use_cxx_modules = false
use_thin_lto = false
# Disable C++ modules to avoid build issues
use_clang_modules = false
use_autogenerated_modules = false
using_tested_sysroot = false
pdf_is_complete_lib = true
EOF
  
  # Generate build files
  echo "Generating build files..."
  gn gen out/Default
  
  # Build Pdfium as static library
  echo "Building Pdfium (this will take 10-30 minutes)..."
  ninja -C out/Default pdfium
  
  # Create a shared library from the static library
  echo "Creating shared library from static library..."
  cd out/Default
  
  # Find the main pdfium static library
  PDFIUM_STATIC=""
  if [ -f "obj/libpdfium.a" ]; then
    PDFIUM_STATIC="obj/libpdfium.a"
  else
    PDFIUM_STATIC=$(find obj -name "libpdfium.a" -type f | head -1)
  fi
  
  if [ -z "$PDFIUM_STATIC" ] || [ ! -f "$PDFIUM_STATIC" ]; then
    echo "ERROR: libpdfium.a not found"
    echo "Searching for static libraries..."
    find obj -name "*.a" -type f | head -10
    exit 1
  fi
  
  echo "Found static library: $PDFIUM_STATIC"
  
  # Extract object files and collect all FPDF_* symbol names
  echo "Extracting object files from static library..."
  mkdir -p pdfium_objs
  cd pdfium_objs
  ar x "../$PDFIUM_STATIC"
  
  # Collect all FPDF_* symbol names from all object files
  echo "Collecting FPDF_* symbol names..."
  nm *.o 2>/dev/null | grep -E " [tT] .*FPDF_" | awk '{print $3}' | sort -u > ../fpdf_symbols.txt
  
  cd ..
  
  # Create a version script with explicit symbol names
  # The wildcard pattern might not work with hidden symbols, so list them explicitly
  echo "Creating version script with FPDF_* symbols..."
  {
    echo "PDFIUM_1.0 {"
    echo "  global:"
    # Add all FPDF_ symbols explicitly
    while read sym; do
      echo "    $sym;"
    done < fpdf_symbols.txt
    echo "  local:"
    echo "    *;"
    echo "};"
  } > pdfium.version
  
  # Skip objcopy processing - use -Wl,--export-dynamic to export all symbols
  # This exports everything, but ensures FPDF_* symbols are available
  echo "Linking with --export-dynamic to export all symbols..."
  
  # Link with --export-dynamic to force export of all symbols (including hidden ones)
  if command -v ld.gold >/dev/null 2>&1; then
    echo "Using gold linker..."
    g++ -shared -fPIC -o libpdfium.so pdfium_objs/*.o \
      -fuse-ld=gold \
      -Wl,--export-dynamic \
      -Wl,-soname,libpdfium.so \
      -licuuc -licui18n -lfreetype -llcms2 -lopenjpeg -ljpeg -lpng -lz \
      -pthread
  else
    echo "Using default linker..."
    g++ -shared -fPIC -o libpdfium.so pdfium_objs/*.o \
      -Wl,--export-dynamic \
      -Wl,--no-eh-frame-hdr \
      -Wl,-soname,libpdfium.so \
      -licuuc -licui18n -lfreetype -llcms2 -lopenjpeg -ljpeg -lpng -lz \
      -pthread 2>&1 | grep -v "no .eh_frame_hdr table will be created" || true
  fi
  
  # Clean up
  rm -rf pdfium_objs pdfium.version fpdf_symbols.txt
  
  # Verify that FPDF_InitLibraryWithConfig is exported
  if ! nm -D libpdfium.so 2>/dev/null | grep -q "FPDF_InitLibraryWithConfig"; then
    echo "ERROR: FPDF_InitLibraryWithConfig not found in exported symbols"
    echo "Checking all FPDF symbols:"
    nm -D libpdfium.so 2>/dev/null | grep "FPDF_" | head -10
    exit 1
  fi
  
  echo "Successfully created libpdfium.so with exported symbols"
  
  echo "Successfully created libpdfium.so"
  
  cd ../..
}

package() {
  # Find the actual pdfium directory (gclient may create nested structure)
  if [ -d "$srcdir/pdfium/pdfium" ]; then
    cd "$srcdir/pdfium/pdfium"
  else
    cd "$srcdir/pdfium"
  fi
  
  # The shared library should be in out/Default (created in build())
  PDFIUM_LIB="out/Default/libpdfium.so"
  
  if [ -z "$PDFIUM_LIB" ] || [ ! -f "$PDFIUM_LIB" ]; then
    echo "ERROR: Could not find libpdfium.so"
    echo "Searching in out/Default..."
    find out/Default -name "*.so" -type f
    echo ""
    echo "Listing out/Default directory:"
    ls -la out/Default/ | head -20
    exit 1
  fi
  
  echo "Found Pdfium library at: $PDFIUM_LIB"
  
  # Verify symbols are exported before installing
  if ! nm -D "$PDFIUM_LIB" 2>/dev/null | grep -q "FPDF_InitLibraryWithConfig"; then
    echo "ERROR: FPDF_InitLibraryWithConfig not exported in library"
    exit 1
  fi
  
  # Install library (don't strip - it removes symbols)
  install -Dm755 "$PDFIUM_LIB" "$pkgdir/usr/lib/libpdfium.so"
  
  # Create a symlink for compatibility
  ln -sf libpdfium.so "$pkgdir/usr/lib/libpdfium.so.1"
  
  # Install headers (if needed for development)
  if [ -d "public" ]; then
    mkdir -p "$pkgdir/usr/include/pdfium"
    cp -r public/* "$pkgdir/usr/include/pdfium/" 2>/dev/null || true
  fi
  
  # Install license
  if [ -f "LICENSE" ]; then
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
  fi
}

